// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl = process.env["POSTGRES_URI"] ?? process.env["DATABASE_URL"];
const shadowDatabaseUrl = process.env["SHADOW_DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl,
    // Optional: dedicated shadow DB avoids create/drop on cloud Postgres and can speed migrate dev.
    // Must be a different database name than `url` (e.g. same host, db suffix `_shadow`).
    ...(shadowDatabaseUrl ? { shadowDatabaseUrl } : {}),
  },
});
